# Generated by Django 2.1.2 on 2018-10-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('application_id', models.CharField(max_length=100, verbose_name='application_id')),
                ('env', models.CharField(max_length=100, verbose_name='env')),
                ('subenv', models.CharField(max_length=100, verbose_name='subenv')),
                ('started_at', models.CharField(max_length=100, verbose_name='started_at')),
                ('finished_at', models.CharField(max_length=100, verbose_name='finished_at')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
